In [56]:
import pandas as pd

df = pd.read_csv('overall.csv')
df.head()

   consumer_id  provider_id      score
0            4           11   0.000000
1            4           15  57.142857
2            4           20  71.428571
3            4           25  84.615385
4            4           37  68.421053

In [2]:
df2 = pd.crosstab(df['consumer_id'], df['provider_id'])
df2.head()

provider_id,4,6,7,8,10,11,12,14,15,16,...,34,35,37,38,39,40,42,43,44,45
consumer_id,,,,,,,,,,,,,,,,,,,,,
4,0,0,0,0,0,1,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
6,0,1,0,0,0,0,0,0,0,0,...,1,1,0,0,0,1,0,0,1,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,1,0,0
8,0,0,0,1,0,0,1,1,0,1,...,0,1,0,1,1,1,1,1,1,0
10,0,0,0,0,1,0,0,0,0,0,...,0,1,1,1,0,0,1,0,1,0

In [3]:
def encode(item_freq):
    res = 0
    if item_freq > 0:
        res = 1
    return res

basket_input = df2.applymap(encode)
basket_input

provider_id,4,6,7,8,10,11,12,14,15,16,...,34,35,37,38,39,40,42,43,44,45
consumer_id,,,,,,,,,,,,,,,,,,,,,
4,0,0,0,0,0,1,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
6,0,1,0,0,0,0,0,0,0,0,...,1,1,0,0,0,1,0,0,1,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,1,0,0
8,0,0,0,1,0,0,1,1,0,1,...,0,1,0,1,1,1,1,1,1,0
10,0,0,0,0,1,0,0,0,0,0,...,0,1,1,1,0,0,1,0,1,0
11,0,0,0,1,0,1,0,0,1,1,...,0,1,1,1,1,1,1,0,1,1
12,0,0,0,1,0,0,1,1,0,0,...,0,0,0,1,0,0,0,1,0,0
14,0,0,0,1,0,0,1,1,0,1,...,0,0,0,1,0,0,0,1,0,0
15,1,0,0,1,0,1,0,0,0,0,...,0,1,1,0,0,0,0,0,1,1
16,0,1,0,1,0,1,0,1,0,1,...,1,1,1,1,1,0,1,0,1,1
17,0,1,1,1,1,1,0,0,1,1,...,1,1,1,1,1,0,1,1,1,1
18,0,0,0,1,0,0,0,0,0,0,...,1,1,0,0,0,0,1,0,0,0
19,0,1,0,1,1,1,1,1,0,1,...,1,1,1,1,1,0,1,1,1,1
20,1,1,0,0,0,1,0,0,1,0,...,0,1,1,1,0,0,0,0,1,0
21,1,0,1,1,0,1,0,0,0,1,...,0,1,1,1,1,0,1,1,0,0
22,0,1,0,1,1,1,0,0,0,1,...,1,1,1,1,1,1,1,0,1,1
24,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
25,1,0,0,0,1,1,0,0,1,0,...,1,1,1,1,0,0,0,0,1,0
26,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
27,0,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
28,0,1,1,1,0,1,0,1,0,1,...,1,1,1,1,0,1,1,1,1,1
29,0,1,0,1,0,1,1,1,0,1,...,1,1,0,1,1,1,1,0,1,1
32,0,1,0,1,1,1,0,0,0,1,...,0,1,1,1,1,1,1,0,1,1
33,0,1,0,1,0,1,1,0,0,1,...,1,1,1,1,1,1,1,1,1,1
34,0,1,0,0,0,0,0,0,0,1,...,1,1,0,1,1,0,1,1,0,1
35,0,1,0,1,1,1,1,1,0,1,...,0,1,1,1,1,1,1,1,1,1
37,1,0,0,0,0,1,0,0,1,1,...,0,1,1,0,0,0,0,0,1,0
38,0,0,1,1,1,1,1,1,0,1,...,1,1,0,1,0,0,1,1,1,1
39,0,0,0,1,0,1,0,0,0,1,...,1,1,0,0,1,0,1,0,1,1
40,0,1,0,1,1,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
42,0,0,1,1,1,1,0,0,0,1,...,0,1,1,1,1,0,1,0,1,1
43,0,0,0,1,0,0,1,1,0,0,...,1,1,0,1,0,0,0,0,0,0
44,0,1,0,1,1,1,0,0,0,1,...,0,1,1,1,0,1,1,0,1,1
45,1,0,0,1,1,1,0,0,1,1,...,1,1,1,1,1,0,1,0,1,1

In [58]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules


frequent_itemsets = fpgrowth(basket_input, min_support=0.6, use_colnames=True)
# frequent_itemsets = apriori(basket_input.astype(bool), min_support=0.5, use_colnames=True)

/Users/ayaki/Documents/TIDE 2023/team-valkyrie-1/env/lib/python3.9/site-packages/mlxtend/frequent_patterns/fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [77]:
rules = association_rules(frequent_itemsets, metric="lift")

rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(19),(35),0.794118,0.852941,0.735294,0.925926,1.085568,0.057958,1.985294
1,(35),(19),0.852941,0.794118,0.735294,0.862069,1.085568,0.057958,1.492647
2,(35),(22),0.852941,0.764706,0.764706,0.896552,1.172414,0.112457,2.274510
3,(22),(35),0.764706,0.852941,0.764706,1.000000,1.172414,0.112457,inf
4,(19),(22),0.794118,0.764706,0.676471,0.851852,1.113960,0.069204,1.588235

In [78]:
rules = rules[rules['antecedents'].apply(list).apply(len) == 1]

rules['antecedents'] = rules['antecedents'].apply(list).apply(lambda x: x[0] if len(x) == 1 
                                                              else '-'.join([str(arg) for arg in x])).astype(str)

In [79]:
rules['consequents'] = rules['consequents'].apply(list).apply(lambda x: x[0] if len(x) == 1
                                                              else '-'.join([str(arg) for arg in x])).astype(str)

In [80]:
result = rules.query('confidence > 0.85').groupby('antecedents')['consequents'].apply(lambda x: '-'.join(x)
                                                                                     ).reset_index()
result

  antecedents                                        consequents
0          17  35-29-19-28-22-38-33-35-29-35-19-19-29-35-19-2...
1          19                            35-22-35-22-28-29-38-33
2          22                                        35-19-35-19
3          28                            19-35-33-35-19-29-35-29
4          29  19-35-28-33-35-19-35-28-19-28-35-19-28-33-35-3...
5          33                                        28-29-19-35
6          35                                              19-22
7          38                            17-19-33-35-33-19-35-19
8          44       35-19-28-22-35-19-35-28-19-22-35-22-35-19-22
9           8                                        35-29-33-19

In [81]:
result.to_csv('output.csv', index=False)